[package]
name = "guessing_game_edg"
version = "0.1.0"
edition = "2021"
description = "fun game where you can try your luck!"
license = "MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
